version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
      - web

  api:
    build:
      context: ./projects/api
      dockerfile: dev.dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./projects/api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      - VIRTUAL_HOST=api.dev.loop.com
      - VIRTUAL_PORT=4000
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=loop_dev

  web:
    build:
      context: ./projects/web
      dockerfile: dev.dockerfile
    ports:
      - "3000:4000"
    volumes:
      - ./projects/web:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VIRTUAL_HOST=dev.loop.com
      - VIRTUAL_PORT=4000
      - NODE_ENV=development


  postgres:
    image: postgres:10.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=loop_dev

volumes:
  postgres_data:
