version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  api:
    build:
      context: ./projects/api
      dockerfile: dev.dockerfile
    depends_on:
      - postgres
    volumes:
      - ./projects/api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - VIRTUAL_HOST=api.margaret.com
      - VIRTUAL_PORT=4000
      - GRAPHQL_SERVER_PORT=4000

  postgres:
    image: postgres:10.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      -

volumes:
  postgres_data
