apiVersion: skaffold/v1alpha2
kind: Config

build:
  artifacts:
    - imageName: looporg/api
      workspace: ./projects/api
      docker:
        dockerfilePath: Dockerfile

  local:
    skipPush: false

deploy:
  helm:
    releases:
      - name: loop
        chartPath: ./k8s/loop
        setValues:
          googleClientSecret: $GOOGLE_CLIENT_SECRET
          facebookClientSecret: $FACEBOOK_CLIENT_SECRET
          githubClientSecret: $GITHUB_CLIENT_SECRET
