apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.api.componentName }}-deployment
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Values.appName }}
    component: {{ .Values.api.componentName }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      component: {{ .Values.api.componentName }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app: {{ .Values.appName }}
        component: {{ .Values.api.componentName }}
    spec:
      containers:
        - name: {{ .Values.api.componentName }}
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          ports:
            - containerPort: {{ .Values.api.serverPort }}

          volumeMounts:
            - name: {{ .Values.api.componentName }}-secrets
              mountPath: "/usr/src/app/dist/keys"
              readOnly: true

          livenessProbe:
            httpGet:
              path: {{ .Values.api.healthinessProbePath }}
              port: {{ .Values.api.serverPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: {{ .Values.api.readinessProbePath }}
              port: {{ .Values.api.serverPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3

      volumes:
        - name: {{ .Values.api.componentName }}-secrets
          secret:
            secretName: {{ .Release.Name }}-{{ .Values.api.componentName }}-secrets
