apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Values.appName }}
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rules:
  - host: {{ .Values.domainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.web.componentName }}-service
          servicePort: 80
  - host: api.{{ .Values.domainName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-{{ .Values.api.componentName }}-service
          servicePort: 80
