apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.web.componentName }}-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ .Values.appName }}
    component: {{ .Values.web.componentName }}
data:
  google-client-id: {{ .Values.googleClientId }}
  facebook-client-id: {{ .Values.facebookClientId }}
  github-client-id: {{ .Values.githubClientId }}
