apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-deployment
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: loop
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loop
      component: web
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app: loop
        component: web
    spec:
      containers:
        - name: web
          image: looporg/web:latest
          ports:
            - containerPort: 4000
