apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-api-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: collectr
    component: api
data:
  google-client-id: {{ .Values.googleClientId }}
  facebook-client-id: {{ .Values.facebookClientId }}
  github-client-id: {{ .Values.githubClientId }}
